<?php
/**
 * Persian translations for the keyword dictionaries that live in the DATABASE,
 * not in a lang JSON file:
 *
 *   languages.customer_keywords        - booking / checkout / tenant strings
 *   user_languages.keywords (per user) - the tenant's own site labels
 *
 * Both use the same key space: the 219 customer_keywords keys plus the two keys
 * only the per-user rows carry (Serial_No_ and Thanks_&_Regards). getUserLanguageKeywords()
 * and the booking controllers read these dictionaries straight out of the DB,
 * so a missing Persian row means the tenant site renders English labels even
 * when the locale is fa.
 *
 * Payment gateway names are proper nouns and deliberately stay Latin - they are
 * brand marks, not interface text. BRAND_KEYS lists them so the harness can
 * allow exactly those and reject any other untranslated value.
 */

$brands = [
    'Facebook', 'Twitter', 'Linkedin', 'Mercadopago', 'Mollie', 'Flutterwave',
    'Razorpay', 'Paytm', 'Paystack', 'Instamojo', 'Stripe', 'Paypal',
    'Authorize_net',
];

return [
    // ---- tenant site: navigation and profile --------------------------------
    'Hire_me' => 'استخدام من',
    'My_Resume' => 'رزومه من',
    'About_Me' => 'درباره من',
    'Technical_Skills' => 'مهارت‌های فنی',
    'Skills' => 'مهارت‌ها',
    'Services' => 'خدمات',
    'What_I_Do' => 'کاری که انجام می‌دهم',
    'Experience' => 'سوابق',
    'Present' => 'اکنون',
    'Home' => 'خانه',
    'Portfolios' => 'نمونه‌کارها',
    'Blogs' => 'وبلاگ‌ها',
    'Contact' => 'تماس',
    'Download_CV' => 'دانلود رزومه',
    'Job' => 'شغل',
    'Education' => 'تحصیلات',
    'All' => 'همه',
    'Name' => 'نام',
    'Email_Address' => 'آدرس ایمیل',
    'Subject' => 'موضوع',
    'Message' => 'پیام',
    'Send_Message' => 'ارسال پیام',
    'Stay_Connected' => 'در ارتباط باشید',
    'Service_Details' => 'جزئیات خدمت',
    'Categories' => 'دسته‌بندی‌ها',
    'Portfolio_Details' => 'جزئیات نمونه‌کار',
    'Related_Portfolios' => 'نمونه‌کارهای مرتبط',
    'by' => 'توسط',
    'Search_Here' => 'اینجا جستجو کنید',
    'Search_your_keyword' => 'کلمه کلیدی خود را بنویسید',
    'Latest_Blogs' => 'جدیدترین نوشته‌ها',
    'Blog_Details' => 'جزئیات نوشته',
    'Facebook' => 'Facebook',
    'Twitter' => 'Twitter',
    'Linkedin' => 'LinkedIn',
    "Hi_I'm," => 'سلام، من',
    'Read_More' => 'ادامه مطلب',
    'Read_All_Post' => 'همه نوشته‌ها',
    'I_am' => 'من',
    'About' => 'درباره',

    // ---- contact form -------------------------------------------------------
    'Enter_Email_Address' => 'ایمیل خود را وارد کنید',
    'Enter_Name' => 'نام خود را وارد کنید',
    'Enter_Subject' => 'موضوع را وارد کنید',
    'Enter_Message' => 'پیام خود را وارد کنید',

    // ---- testimonials / appointment -----------------------------------------
    'Testimonial' => 'نظر مشتری',
    'Testimonials' => 'نظرات مشتریان',
    'Get_in_touch' => 'تماس بگیرید',
    'Appointment' => 'نوبت‌دهی',
    'Email' => 'ایمیل',

    // ---- auth ---------------------------------------------------------------
    'Enter_password' => 'رمز عبور را وارد کنید',
    'Donot_have_an_account' => 'حساب کاربری ندارید؟',
    'New_user' => 'کاربر جدید',
    'Book_as_guest' => 'رزرو به‌عنوان مهمان',
    'OR' => 'یا',
    'Next' => 'بعدی',
    'choose_a_date_to_see_slots' => 'برای دیدن زمان‌های آزاد یک تاریخ انتخاب کنید',
    'Select_a_slot' => 'یک بازه زمانی انتخاب کنید',
    'Select_a_date' => 'یک تاریخ انتخاب کنید',
    'Signout' => 'خروج',
    'Profile' => 'پروفایل',
    'My_Profile' => 'پروفایل من',
    'Confirm' => 'تأیید',
    'Choose_an_option' => 'یک گزینه انتخاب کنید',

    // ---- booking and payment -------------------------------------------------
    'Advance' => 'پرداخت',
    'Payable_amount' => 'مبلغ قابل پرداخت',
    'Catgory' => 'دسته‌بندی',
    'Booking_Time' => 'ساعت رزرو',
    'Booking_Date' => 'تاریخ رزرو',
    'Appointment_summary' => 'خلاصه نوبت',
    'Payment' => 'پرداخت',
    'Checkout' => 'تسویه حساب',
    'forget_password' => 'رمز عبور را فراموش کرده‌اید؟',
    'Send_Mail' => 'ارسال ایمیل',
    'Payment_Method' => 'روش پرداخت',
    'Total_Fee' => 'مبلغ کل',
    'Login' => 'ورود',
    'Payment_Success' => 'پرداخت موفق',
    'Back_to_Home' => 'بازگشت به خانه',
    'Signup' => 'ثبت‌نام',
    'Confirm_Password' => 'تأیید رمز عبور',
    'Copyright' => 'حق نشر',
    'All_Right_Reserved' => 'تمامی حقوق محفوظ است',
    'save_change' => 'ذخیره تغییرات',
    'This_time_slot_is_booked_Please_try_another_slot' => 'این بازه زمانی رزرو شده است! لطفاً بازه دیگری انتخاب کنید',
    'Transaction_Id' => 'شناسه تراکنش',
    'Transaction_ID' => 'شناسه تراکنش',
    'SL_No' => 'ردیف',
    'Serial_No' => 'ردیف',
    'Serial_No_' => 'ردیف',
    'Enter_username' => 'نام کاربری را وارد کنید',
    'Password' => 'رمز عبور',
    'User_name' => 'نام کاربری',
    'account_information' => 'اطلاعات حساب',

    // ---- dashboard / profile -------------------------------------------------
    'Change_Password' => 'تغییر رمز عبور',
    'My_Appointments' => 'نوبت‌های من',
    'No_Appointment_Found' => 'نوبتی یافت نشد',
    'Edit_Profile' => 'ویرایش پروفایل',
    'Logout' => 'خروج',
    'Phone' => 'تلفن',
    'Update_profile' => 'به‌روزرسانی پروفایل',
    'Confirm_New_Password' => 'تأیید رمز عبور جدید',
    'Current_Password' => 'رمز عبور فعلی',
    'Update_Password' => 'به‌روزرسانی رمز عبور',
    'Profile_Settings' => 'تنظیمات پروفایل',
    'New_Password' => 'رمز عبور جدید',
    'Dashboard' => 'پیشخوان',

    // ---- appointment records ---------------------------------------------------
    'appointment_details' => 'جزئیات نوبت',
    'Customer_Details' => 'اطلاعات مشتری',
    'Booking_Day' => 'روز رزرو',
    'Category' => 'دسته‌بندی',
    'Status' => 'وضعیت',
    'Pending' => 'در انتظار',
    'Approved' => 'تأییدشده',
    'Completed' => 'تکمیل‌شده',
    'Rejected' => 'ردشده',
    'Payment_status' => 'وضعیت پرداخت',
    'Payment_Status' => 'وضعیت پرداخت',
    'Paid' => 'پرداخت‌شده',
    'Advanced' => 'پیشرفته',
    'Paid_Fee' => 'مبلغ پرداخت‌شده',
    'Time_slots' => 'بازه‌های زمانی',
    'Time_Slot' => 'بازه زمانی',
    'Details' => 'جزئیات',
    'Due_amount' => 'مبلغ باقی‌مانده',
    'Due_Amount' => 'مبلغ باقی‌مانده',
    'Paid_Amount' => 'مبلغ پرداخت‌شده',
    'Total_Amount' => 'مبلغ کل',
    'Close' => 'بستن',
    'Download' => 'دانلود',
    'payment_method' => 'روش پرداخت',
    'Amount' => 'مبلغ',
    'Customer' => 'مشتری',
    'Free' => 'رایگان',

    // ---- payment gateways (proper nouns, kept in Latin on purpose) -------------
    'Mercadopago' => 'Mercadopago',
    'Mollie' => 'Mollie',
    'Flutterwave' => 'Flutterwave',
    'Razorpay' => 'Razorpay',
    'Paytm' => 'Paytm',
    'Paystack' => 'Paystack',
    'Instamojo' => 'Instamojo',
    'Stripe' => 'Stripe',
    'Paypal' => 'Paypal',
    'Authorize_net' => 'Authorize.net',

    // ---- misc labels ------------------------------------------------------------
    'Instructions' => 'راهنما',
    'Short_Description' => 'توضیح کوتاه',
    'Time' => 'ساعت',
    'Day' => 'روز',
    'Date' => 'تاریخ',
    'Open' => 'باز',
    'Closed' => 'بسته',
    'Business_Day_Of_Appointment' => 'روز کاری نوبت',
    'Gallery' => 'گالری',
    'Blog' => 'وبلاگ',
    'Account' => 'حساب',
    'Stay_Connected_With_Me' => 'با من در ارتباط باشید',
    'Book_Now' => 'همین حالا رزرو کنید',
    'Make_Appointment' => 'نوبت بگیرید',
    'star_of' => 'از',
    'review' => 'نظر',
    'Thanks_Regards' => 'با احترام',
    'Thanks_&_Regards' => 'با احترام',

    // ---- validation / flash messages ----------------------------------------------
    'fullname_required' => 'نام و نام خانوادگی الزامی است',
    'email_required' => 'ایمیل الزامی است',
    'email_invalid' => 'لطفاً یک ایمیل معتبر وارد کنید',
    'subject_required' => 'موضوع الزامی است',
    'message_required' => 'پیام الزامی است',
    'Mail_sent_successfully' => 'ایمیل با موفقیت ارسال شد!',
    'Lost_your_password' => 'رمز عبور را فراموش کرده‌اید؟',
    'password_required' => 'فیلد رمز عبور الزامی است',
    'email_not_verified' => 'لطفاً ایمیل خود را تأیید کنید',
    'account_deactivated' => 'متأسفیم، حساب کاربری شما غیرفعال شده است',
    'credentials_mismatch' => 'اطلاعات واردشده با سوابق ما مطابقت ندارد',
    'mail_sent_success' => 'ایمیل به نشانی شما ارسال شد',
    'mail_send_error' => 'ارسال ایمیل ناموفق بود',
    'user_not_found' => 'کاربری با این ایمیل یافت نشد',
    'reset_password' => 'بازنشانی رمز عبور',
    'new_password_required' => 'فیلد رمز عبور جدید الزامی است',
    'new_password_confirmed' => 'تأیید رمز عبور جدید ناموفق بود',
    'new_password_confirmation_required' => 'فیلد تأیید رمز عبور جدید الزامی است',
    'password_updated_successfully' => 'رمز عبور با موفقیت به‌روزرسانی شد',
    'username_required' => 'فیلد نام کاربری الزامی است',
    'username_max' => 'نام کاربری نمی‌تواند بیش از ۲۵۵ نویسه باشد',
    'email_max' => 'ایمیل نمی‌تواند بیش از ۲۵۵ نویسه باشد',
    'password_confirmed' => 'تأیید رمز عبور ناموفق بود',
    'password_confirmation_required' => 'فیلد تأیید رمز عبور الزامی است',
    'username_taken' => 'این نام کاربری قبلاً انتخاب شده است',
    'email_taken' => 'این ایمیل قبلاً ثبت شده است',
    'email_verification_needed' => 'باید ایمیل شما را تأیید کنیم. پیامی به نشانی شما ارسال شد',
    'email_verification_instruction' => 'برای تأیید ایمیل، لطفاً روی پیوند داخل همان پیام کلیک کنید',
    'email_verification_subject_missing' => 'موضوع ایمیل تأیید خالی است',
    'email_verification_body_missing' => 'متن ایمیل تأیید خالی است',
    'click_here' => 'اینجا کلیک کنید',
    'verification_mail_sent' => 'ایمیل تأیید به نشانی شما ارسال شد',
    'email_verified_success' => 'ایمیل شما با موفقیت تأیید شد',
    'email_verification_failed' => 'تأیید ایمیل ناموفق بود',
    'Submit' => 'ثبت',
    'name_required' => 'فیلد نام الزامی است',
    'the' => 'مقاله',
    'field_is_required' => 'الزامی است',
    'only' => 'فقط',
    'files_are_allowed' => 'مجاز است',
    'Please_select_a_timeslot' => 'لطفاً یک بازه زمانی انتخاب کنید',
    'this_time_slot_is_booked' => 'این بازه زمانی رزرو شده است',
    'please_try_another_slot' => 'لطفاً بازه دیگری انتخاب کنید',

    // ---- address / days -----------------------------------------------------------
    'Address' => 'نشانی',
    'State' => 'استان',
    'City' => 'شهر',
    'Country' => 'کشور',
    'Actions' => 'عملیات',
    'Monday' => 'دوشنبه',
    'Tuesday' => 'سه‌شنبه',
    'Wednesday' => 'چهارشنبه',
    'Thursday' => 'پنجشنبه',
    'Friday' => 'جمعه',
    'Saturday' => 'شنبه',
    'Sunday' => 'یکشنبه',
    'First_Name' => 'نام',
    'Last_Name' => 'نام خانوادگی',
    'profile_updated_successfully' => 'پروفایل با موفقیت به‌روزرسانی شد',
    'current_password_required' => 'فیلد رمز عبور فعلی الزامی است',
    'Receipt_image_must_be' => 'تصویر رسید باید باشد',
];
