<?php
/**
 * Persian translations for user-dashboard-namespace keys the views ask for
 * but that are absent from user_en.json - the gaps found by
 * tests/lang_coverage_audit.php.
 *
 * Same shape as admin_fa_view_gaps.php: mostly the payment-gateway settings
 * form, the Enamad panel and the watermark panel, all of which are
 * English-only strings hardcoded in the user-dashboard blades.
 *
 * Consumed by tests/_build_user_fa.php.
 */

return [
    // ---- identity / account -------------------------------------------------------------
    'Account Information' => 'اطلاعات حساب',
    'My Profile' => 'نمایهٔ من',
    'Go to Dashboard' => 'رفتن به پیشخوان',
    'Follow Us' => 'ما را دنبال کنید',
    'Email Address*' => 'نشانی ایمیل *',
    'Enter email address' => 'نشانی ایمیل را وارد کنید',
    'Enter password' => 'رمز عبور را وارد کنید',
    'Enter Address' => 'نشانی را وارد کنید',
    'Enter Phone Number' => 'شمارهٔ تلفن را وارد کنید',
    'Enter company' => 'نام شرکت را وارد کنید',
    'Enter Occupation' => 'شغل را وارد کنید',
    'Enter Name' => 'نام را وارد کنید',
    'Enter Value' => 'مقدار را وارد کنید',
    'Enter rating' => 'امتیاز را وارد کنید',
    'Enter video url' => 'نشانی ویدیو را وارد کنید',
    'Enter Serial Numbers' => 'شماره‌های ترتیب را وارد کنید',
    'Enter subject of E-mail' => 'موضوع ایمیل را وارد کنید',
    'Enter Email' => 'ایمیل را وارد کنید',
    'Identity Number' => 'کد ملی',
    'Zip Code' => 'کد پستی',
    'Current Password' => 'رمز عبور فعلی',
    'Confirm New Password' => 'تکرار رمز عبور جدید',
    'Reset Password' => 'بازنشانی رمز عبور',
    'Lost your password' => 'رمز عبور خود را فراموش کرده‌اید؟',
    'Signup' => 'ثبت‌نام',
    'Sign Out' => 'خروج',
    'Choose an option' => 'یک گزینه انتخاب کنید',
    'Confirm' => 'تأیید',
    'Rate' => 'نرخ',
    'OR' => 'یا',
    'in' => 'در',
    // not in user_en.json; the gateway settings form hardcodes it
    'Token' => 'توکن',
    // hardcoded currency label in the pricing/information panel
    '1 USD' => '۱ دلار',
    // the blade used to call this with an embedded newline, which can never
    // match a JSON key; collapsed to one line in views/user/cv/create.blade.php
    'Your Name, Your Occupation' => 'نام شما، شغل شما',
    'Keyword' => 'کلیدواژه',
    'Enter Keyword' => 'کلیدواژه را وارد کنید',
    'Add New Keyword' => 'افزودن کلیدواژهٔ جدید',
    'Leave empty to use default' => 'خالی بگذارید تا مقدار پیش‌فرض استفاده شود',
    'Advance' => 'پیش‌پرداخت',
    'Book as guest' => 'تکمیل خرید به‌عنوان مهمان',
    'Duration, Title, Subtitle, Description' => 'مدت، عنوان، زیرعنوان، توضیحات',
    'Designation Text' => 'متن عنوان شغلی',
    'Summary Section Background Color' => 'رنگ پس‌زمینهٔ بخش خلاصه',
    'Profile' => 'نمایه',
    'Profile Id' => 'شناسهٔ نمایه',
    'Features' => 'ویژگی‌ها',
    'Gallery' => 'گالری',
    'Add Feature' => 'افزودن ویژگی',
    'Edit Feature' => 'ویرایش ویژگی',
    'NO FEATURE FOUND' => 'ویژگی‌ای یافت نشد',
    'Add Gallery' => 'افزودن گالری',
    'NO GALLERY IMAGE FOUND' => 'تصویر گالری یافت نشد',
    'The higher the serial number is, the later the gallery image will be shown' => 'هرچه شماره بیشتر باشد، تصویر گالری دیرتر نمایش داده می‌شود',
    'Add Post' => 'افزودن نوشته',
    'Edit Post' => 'ویرایش نوشته',
    'NO WORK PROCESS FOUND' => 'فرایند کاری یافت نشد',
    'NO SUBSCRIBER FOUND' => 'مشترکی یافت نشد',
    'Search by Email' => 'جستجو بر اساس ایمیل',
    'Send Mail' => 'ارسال ایمیل',
    'Select a Language' => 'زبانی انتخاب کنید',
    'Step 1' => 'گام ۱',
    'Step 2' => 'گام ۲',
    'UPDATE FIELD' => 'به‌روزرسانی فیلد',
    'No Appointment Found!' => 'نوبتی یافت نشد!',
    'No Followers Found' => 'دنبال‌کننده‌ای یافت نشد',
    'Time slot' => 'بازهٔ زمانی',
    'NB: click on the dropdown sign to select an icon.' => 'توجه: برای انتخاب آیکون روی علامت کشویی کلیک کنید.',
    'Your Name, Your' => 'نام شما،',

    // ---- payments ---------------------------------------------------------------------
    'Payment Success' => 'پرداخت موفق',
    'Payment method' => 'روش پرداخت',
    'Payment status' => 'وضعیت پرداخت',
    'Package Purchase via Midtrans' => 'خرید بسته از طریق میدترنس',
    'Pay Now' => 'همین حالا پرداخت کنید',
    'Due Amount' => 'مبلغ پرداخت‌نشده',
    'Success URL' => 'نشانی موفقیت',
    'Cancel URL' => 'نشانی لغو',
    'payment_success' => 'پرداخت موفق',

    // ---- mail -----------------------------------------------------------------------
    'Mail From Admin' => 'ایمیل از مدیر',
    'Mail To Admin' => 'ایمیل به مدیر',
    'This mail address will be used to send all mails from this website.' => 'این نشانی ایمیل برای ارسال همهٔ ایمیل‌های این سایت استفاده می‌شود.',
    'This mail address will be used to receive all mails from clients.' => 'این نشانی ایمیل برای دریافت همهٔ ایمیل‌های مشتریان استفاده می‌شود.',
    'From Email*' => 'ایمیل فرستنده *',
    'From Name*' => 'نام فرستنده *',
    'SMTP Host*' => 'میزبان SMTP *',
    'SMTP Port*' => 'درگاه SMTP *',
    'SMTP Username*' => 'نام کاربری SMTP *',
    'SMTP Password*' => 'رمز عبور SMTP *',
    'SMTP Status*' => 'وضعیت SMTP *',
    'Encryption*' => 'رمزنگاری *',

    // ---- Enamad ----------------------------------------------------------------------------
    'Enamad Settings' => 'تنظیمات اینماد',
    'Enamad Status' => 'وضعیت اینماد',
    'Enamad Code' => 'کد اینماد',
    'Enamad Site ID' => 'شناسهٔ سایت اینماد',
    'Enamad Secret Key' => 'کلید محرمانهٔ اینماد',
    'Enamad Expire Date' => 'تاریخ انقضای اینماد',
    'Site ID from Enamad' => 'شناسهٔ سایت از اینماد',
    'Secret Key from Enamad' => 'کلید محرمانه از اینماد',
    'Logo Type' => 'نوع لوگو',

    // ---- watermark ------------------------------------------------------------------------------
    'Watermark Badge Settings' => 'تنظیمات نشان واترمارک',
    'Update Watermark Badge' => 'به‌روزرسانی نشان واترمارک',
    'Watermark Badge' => 'نشان واترمارک',
    'Watermark Text' => 'متن واترمارک',
    'Watermark Image' => 'تصویر واترمارک',
    'Current watermark image' => 'تصویر فعلی واترمارک',
    'Watermark Status' => 'وضعیت واترمارک',
    'Watermark Link URL' => 'نشانی لینک واترمارک',
    'Optional link when watermark is clicked' => 'لینک اختیاری هنگام کلیک روی واترمارک',
    'Text to display when no image is provided' => 'متنی که در نبود تصویر نمایش داده می‌شود',
    'Optional image (max 2MB). If provided, text will be ignored.' => 'تصویر اختیاری (حداکثر ۲ مگابایت). اگر ارائه شود، متن نادیده گرفته می‌شود.',
    'e.g. Secure Payment with Bank Mellat' => 'مثال: پرداخت امن با بانک ملت',

    // ---- payment gateways: shared field labels -----------------------------------------------------------
    'API Endpoint' => 'نقطهٔ پایانی API',
    'API Key' => 'کلید API',
    'Callback URL' => 'نشانی بازگشت',
    'Category Code' => 'کد دسته',
    'Merchant Id' => 'شناسهٔ پذیرنده',
    'Merchant ID' => 'شناسهٔ پذیرنده',
    'Salt Index' => 'اندیس Salt',
    'Salt Key' => 'کلید Salt',
    'Sandbox Status' => 'وضعیت سندباکس',
    'Secret Key' => 'کلید محرمانه',
    'Server Key' => 'کلید سرور',
    'Terminal ID' => 'شناسهٔ پایانه',
    'Enable sandbox mode for testing' => 'حالت سندباکس را برای آزمایش فعال کنید',

    // ---- Iranian / regional gateways ------------------------------------------------------------------------
    'Bank Mellat' => 'بانک ملت',
    'Bank Mellat Status' => 'وضعیت بانک ملت',
    'You can get your Terminal ID from Bank Mellat dashboard' => 'شناسهٔ پایانهٔ خود را از پنل بانک ملت دریافت کنید',
    'Iyzico' => 'ای‌زیکو',
    'Iyzico Api Key' => 'کلید API ای‌زیکو',
    'Iyzico Secret Key' => 'کلید محرمانهٔ ای‌زیکو',
    'Iyzico Status' => 'وضعیت ای‌زیکو',
    'Iyzico Test Mode' => 'حالت تست ای‌زیکو',
    'ZarinPal' => 'زرین‌پال',
    'ZarinPal Status' => 'وضعیت زرین‌پال',
    'Zibal' => 'زیبال',
    'Zibal Status' => 'وضعیت زیبال',
    'IDPay' => 'آیدی‌پی',
    'IDPay Status' => 'وضعیت آیدی‌پی',
    'NextPay' => 'نکست‌پی',
    'NextPay Status' => 'وضعیت نکست‌پی',
    'Pay.ir' => 'پی‌ایر',
    'Pay.ir Status' => 'وضعیت پی‌ایر',
    'Paytabs' => 'پی‌تبز',
    'Paytabs Status' => 'وضعیت پی‌تبز',
    "You will get your 'API Endpoit' from PayTabs Dashboard." => 'نقطهٔ پایانی API خود را از پنل پی‌تبز دریافت می‌کنید.',
    'Perfect Money' => 'پرفکت مانی',
    'Perfect Money Status' => 'وضعیت پرفکت مانی',
    'Perfect Money Wallet Id' => 'شناسهٔ کیف پول پرفکت مانی',
    'You will get wallet id form here' => 'شناسهٔ کیف پول خود را از اینجا دریافت می‌کنید',
    'Phonepe' => 'فون‌پی',
    'Phonepe Status' => 'وضعیت فون‌پی',
    'Toyyibpay' => 'توییب‌پی',
    'Toyyibpay Status' => 'وضعیت توییب‌پی',
    'Toyyibpay Test Mode' => 'حالت تست توییب‌پی',
    'Xendit' => 'زن‌دیت',
    'Xendit Status' => 'وضعیت زن‌دیت',
    'Yoco' => 'یوکو',
    'Yoco Status' => 'وضعیت یوکو',
    'Midtrans' => 'میدترنس',
    'Midtrans Server Key' => 'کلید سرور میدترنس',
    'Midtrans Status' => 'وضعیت میدترنس',
    'Midtrans Test Mode' => 'حالت تست میدترنس',
    'Set these URLs in Midtrans Dashboard like this' => 'این نشانی‌ها را مانند زیر در پنل میدترنس ثبت کنید',
    'MyFatoorah' => 'مای‌فاتوره',
    'MyFatoorah Status' => 'وضعیت مای‌فاتوره',
];